// This file was auto-generated by snippets/asm.py.
// It handles the linkage of the assembly functions.

// Typedefs.
typedef void(*f265_lbd_dct_func)(int16_t *dst, uint8_t *src, int src_stride, uint8_t *pred, int pred_stride, uint8_t *spill);
typedef void(*f265_hbd_dct_func)(int16_t *dst, int16_t *src, int src_stride, int16_t *pred, int pred_stride, uint8_t *spill);
typedef void(*f265_lbd_idct_func)(uint8_t *dst, int dst_stride, uint8_t *pred, int pred_stride, int16_t *coeffs, uint8_t *spill);
typedef void(*f265_hbd_idct_func)(int16_t *dst, int dst_stride, int16_t *pred, int pred_stride, int16_t *coeffs, uint8_t *spill);
typedef int(*f265_lbd_quant_func)(int16_t *dst, int16_t *src, int bs, int mult, int add, int shift);
typedef int(*f265_hbd_quant_func)(int16_t *dst, int16_t *src, int bs, int mult, int add, int shift);
typedef void(*f265_lbd_dequant_func)(int16_t *dst, int16_t *src, int bs, int mult, int add, int shift);
typedef void(*f265_hbd_dequant_func)(int16_t *dst, int16_t *src, int bs, int mult, int add, int shift);
typedef int(*f265_lbd_fsad_func)(uint8_t *src, int src_stride, uint8_t *ref, int ref_stride, int packed_dims);
typedef int(*f265_hbd_fsad_func)(int16_t *src, int src_stride, int16_t *ref, int ref_stride, int packed_dims);
typedef void(*f265_lbd_sad3_func)(int *costs, uint8_t *src, int src_stride, uint8_t **refs, int ref_stride, int packed_dims);
typedef void(*f265_hbd_sad3_func)(int *costs, int16_t *src, int src_stride, int16_t **refs, int ref_stride, int packed_dims);
typedef void(*f265_lbd_sad4_func)(int *costs, uint8_t *src, int src_stride, uint8_t **refs, int ref_stride, int packed_dims);
typedef void(*f265_hbd_sad4_func)(int *costs, int16_t *src, int src_stride, int16_t **refs, int ref_stride, int packed_dims);
typedef void(*f265_lbd_avg_pix_func)(uint8_t *dst, uint8_t *src0, int src0_stride, uint8_t *src1, int src1_stride, int packed_dims);
typedef void(*f265_hbd_avg_pix_func)(int16_t *dst, int16_t *src0, int src0_stride, int16_t *src1, int src1_stride, int packed_dims);
typedef void(*f265_lbd_interpol_luma_qpel_pix_func)(uint8_t *dst, int dst_stride, uint8_t *src, int src_stride, int frac, int packed_dims, uint8_t *spill);
typedef void(*f265_hbd_interpol_luma_qpel_pix_func)(int16_t *dst, int dst_stride, int16_t *src, int src_stride, int frac, int packed_dims, uint8_t *spill);

// Globals.

// Indices: 4, 8, 16, 32, dst.
extern f265_lbd_dct_func f265_lbd_dct[5];

// Indices: 4, 8, 16, 32, dst.
extern f265_hbd_dct_func f265_hbd_dct[5];

// Indices: 4, 8, 16, 32, dst.
extern f265_lbd_idct_func f265_lbd_idct[5];

// Indices: 4, 8, 16, 32, dst.
extern f265_hbd_idct_func f265_hbd_idct[5];

// Indices: 4, 8, 16, 32.
extern f265_lbd_quant_func f265_lbd_quant[4];

// Indices: 4, 8, 16, 32.
extern f265_hbd_quant_func f265_hbd_quant[4];

// Indices: 4, 8, 16, 32.
extern f265_lbd_dequant_func f265_lbd_dequant[4];

// Indices: 4, 8, 16, 32.
extern f265_hbd_dequant_func f265_hbd_dequant[4];

// Indices: 2, 4, 8, 16, 32, 64, 6, 12, 24, 48.
extern f265_lbd_fsad_func f265_lbd_fsad[10];

// Indices: 2, 4, 8, 16, 32, 64, 6, 12, 24, 48.
extern f265_hbd_fsad_func f265_hbd_fsad[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_lbd_sad3_func f265_lbd_sad3[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_hbd_sad3_func f265_hbd_sad3[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_lbd_sad4_func f265_lbd_sad4[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_hbd_sad4_func f265_hbd_sad4[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_lbd_avg_pix_func f265_lbd_avg_pix[10];

// Indices: X, 4, 8, 16, 32, 64, X, 12, 24, 48.
extern f265_hbd_avg_pix_func f265_hbd_avg_pix[10];

// Indices: X, X, X, 4_h, 4_v, 4_d, 8_h, 8_v, 8_d, 16_h, 16_v, 16_d, 32_h, 32_v, 32_d, 64_h, 64_v, 64_d, X, X, X, 12_h, 12_v, 12_d, 24_h, 24_v, 24_d, 48_h, 48_v, 48_d.
extern f265_lbd_interpol_luma_qpel_pix_func f265_lbd_interpol_luma_qpel_pix[30];

// Indices: X, X, X, 4_h, 4_v, 4_d, 8_h, 8_v, 8_d, 16_h, 16_v, 16_d, 32_h, 32_v, 32_d, 64_h, 64_v, 64_d, X, X, X, 12_h, 12_v, 12_d, 24_h, 24_v, 24_d, 48_h, 48_v, 48_d.
extern f265_hbd_interpol_luma_qpel_pix_func f265_hbd_interpol_luma_qpel_pix[30];


